CA: Qz2zDuRaq2LhuYN94sGN8ebn4unZhxAogh34hpZpump
description: This goofy ahh cat is sitting da door handle
imagelink: https://cdn.discordapp.com/attachments/1191996230750969876/1269033466855428208/GN1SEC0WoAAWhQL.png?ex=66ae9704&is=66ad4584&hm=74e1dcd63f0382a4ab777fcdde5792bb1900051e355f6c5aae6fb766feb4e9a3&
paragraph1: He's here to open your door to financial freedom.
paragraph2: Once you cross the door, you'll be rich
paragraph3: But beware the cat, nothing is for free
title: Handle Cat
year: 2024
